version: '2'

services:

    Usermanager:
        image: akinduko/molly:andela
        ports:
            - 3000:3000
        depends_on:
            - mongodb

    mongodb:
      image: mongo:latest
      ports:
       - "27017:27017"
      volumes:
       - mongodb_volume:/data/db

    mongoClientTemp:
      image: mongo:2.6.7
      container_name: mongoClientTemp
      links:
          - mongodb:mongodb
      command: mongo --host mongodb --eval  "db.getSiblingDB('molly').createUser({user:'molly', pwd:'molly', roles:[{role:'readWrite',db:'molly'}]});"
      depends_on:
       - mongodb

volumes:
    mongodb_volume:
  
